stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: kapolos/buildtest
      pushRemote: true
      registry: index.docker.io
timeout: 60
